services:
  db:
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: sqlpassword
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
  nginx:
    image: nginx:stable
    ports:
      - 80:80
      # - 8000:8000
    # network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/view:/data/www

volumes:
  db_data:
